In [0]:
import pandas as pd
import numpy as np

In [0]:
visits = spark.table("workspace.default.air_visits").toPandas()
stores = spark.table("workspace.default.air_stores").toPandas()
dates = spark.table("workspace.default.date_info").toPandas()

In [0]:
visits["visit_date"] = pd.to_datetime(visits["visit_date"])
dates["calendar_date"] = pd.to_datetime(dates["calendar_date"])

In [0]:
df = visits.merge(dates, left_on="visit_date", right_on="calendar_date", how="left")
df = df.merge(stores, on="air_store_id", how="left")

In [0]:
df.head()

           air_store_id visit_date  ...   latitude   longitude
0  air_ba937bf13d40fb24 2016-01-13  ...  35.658068  139.751599
1  air_ba937bf13d40fb24 2016-01-14  ...  35.658068  139.751599
2  air_ba937bf13d40fb24 2016-01-15  ...  35.658068  139.751599
3  air_ba937bf13d40fb24 2016-01-16  ...  35.658068  139.751599
4  air_ba937bf13d40fb24 2016-01-18  ...  35.658068  139.751599

[5 rows x 10 columns]

In [0]:
df = df.sort_values(["air_store_id", "visit_date"]).reset_index(drop=True)

In [0]:
df.head()

           air_store_id visit_date  ...   latitude   longitude
0  air_00a91d42b08b08d9 2016-07-01  ...  35.694003  139.753595
1  air_00a91d42b08b08d9 2016-07-02  ...  35.694003  139.753595
2  air_00a91d42b08b08d9 2016-07-04  ...  35.694003  139.753595
3  air_00a91d42b08b08d9 2016-07-05  ...  35.694003  139.753595
4  air_00a91d42b08b08d9 2016-07-06  ...  35.694003  139.753595

[5 rows x 10 columns]

In [0]:
df["month"] = df["visit_date"].dt.month
df.head()

           air_store_id visit_date  visitors  ...   latitude   longitude  month
0  air_00a91d42b08b08d9 2016-07-01        35  ...  35.694003  139.753595      7
1  air_00a91d42b08b08d9 2016-07-02         9  ...  35.694003  139.753595      7
2  air_00a91d42b08b08d9 2016-07-04        20  ...  35.694003  139.753595      7
3  air_00a91d42b08b08d9 2016-07-05        25  ...  35.694003  139.753595      7
4  air_00a91d42b08b08d9 2016-07-06        29  ...  35.694003  139.753595      7

[5 rows x 11 columns]

In [0]:
df['is_weekend'] = df["day_of_week"].isin(["Saturday", "Sunday"]).astype(int)
df.head()

           air_store_id visit_date  visitors  ...   longitude month  is_weekend
0  air_00a91d42b08b08d9 2016-07-01        35  ...  139.753595     7           0
1  air_00a91d42b08b08d9 2016-07-02         9  ...  139.753595     7           1
2  air_00a91d42b08b08d9 2016-07-04        20  ...  139.753595     7           0
3  air_00a91d42b08b08d9 2016-07-05        25  ...  139.753595     7           0
4  air_00a91d42b08b08d9 2016-07-06        29  ...  139.753595     7           0

[5 rows x 12 columns]

In [0]:
for k in [1, 7, 14, 28]:
    df[f"lag_{k}"] = df.groupby("air_store_id")["visitors"].shift(k)

In [0]:
df.sample(5)

                air_store_id visit_date  visitors  ... lag_7 lag_14  lag_28
174483  air_b1a72bf1ebf4b8ef 2016-07-24        50  ...  54.0   22.0     NaN
121575  air_7cf5a02c0e01b647 2016-01-23        37  ...  31.0   31.0     NaN
209744  air_d3e7b5952cd09ccb 2017-02-13        25  ...  27.0   27.0    16.0
81918   air_5a9a6cbeeb434c08 2017-02-23         9  ...  23.0    8.0    17.0
32115   air_2634e41551e9807d 2016-01-06        17  ...   NaN    NaN     NaN

[5 rows x 16 columns]

In [0]:
for w in [7, 28]:
    df[f"roll_mean_{w}"] = (
        df.groupby("air_store_id")["visitors"]
          .transform(lambda s: s.shift(1).rolling(w).mean())
    )
    df[f"roll_std_{w}"] = (
        df.groupby("air_store_id")["visitors"]
          .transform(lambda s: s.shift(1).rolling(w).std())
    )

In [0]:
df.sample(5)

                air_store_id visit_date  ...  roll_mean_28 roll_std_28
243071  air_f6b2489ccf873c3b 2016-04-24  ...     16.500000    4.050606
86746   air_5e70fe82f9e4fab6 2017-01-04  ...     15.928571   10.947445
248527  air_fcd4492c83f1c6b9 2016-09-27  ...     29.714286   18.855900
240254  air_f1f9027d4fa8f653 2017-02-28  ...     20.107143   14.563626
43646   air_32460819c7600037 2017-03-24  ...     48.071429   12.863755

[5 rows x 20 columns]

In [0]:
np.log(df["visitors"])

0         3.555348
1         2.197225
2         2.995732
3         3.218876
4         3.367296
            ...
252103    1.791759
252104    0.693147
252105    0.693147
252106    1.386294
252107    1.609438
Name: visitors, Length: 252108, dtype: float64

In [0]:
df["y"] = np.log1p(df["visitors"])

In [0]:
df.head()

           air_store_id visit_date  ...  roll_std_28         y
0  air_00a91d42b08b08d9 2016-07-01  ...          NaN  3.583519
1  air_00a91d42b08b08d9 2016-07-02  ...          NaN  2.302585
2  air_00a91d42b08b08d9 2016-07-04  ...          NaN  3.044522
3  air_00a91d42b08b08d9 2016-07-05  ...          NaN  3.258097
4  air_00a91d42b08b08d9 2016-07-06  ...          NaN  3.401197

[5 rows x 21 columns]

In [0]:
df.count()

air_store_id      252108
visit_date        252108
visitors          252108
calendar_date     252108
day_of_week       252108
holiday_flg       252108
air_genre_name    252108
air_area_name     252108
latitude          252108
longitude         252108
month             252108
is_weekend        252108
lag_1             251279
lag_7             246305
lag_14            240502
lag_28            228904
roll_mean_7       246305
roll_std_7        246305
roll_mean_28      228904
roll_std_28       228904
y                 252108
dtype: int64

In [0]:
engineered = ["lag_1","lag_7","lag_14","lag_28",
              "roll_mean_7","roll_std_7","roll_mean_28","roll_std_28"]

df_model = df.dropna(subset=engineered).reset_index(drop=True)

In [0]:
df_model.count()

air_store_id      228904
visit_date        228904
visitors          228904
calendar_date     228904
day_of_week       228904
holiday_flg       228904
air_genre_name    228904
air_area_name     228904
latitude          228904
longitude         228904
month             228904
is_weekend        228904
lag_1             228904
lag_7             228904
lag_14            228904
lag_28            228904
roll_mean_7       228904
roll_std_7        228904
roll_mean_28      228904
roll_std_28       228904
y                 228904
dtype: int64

In [0]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228904 entries, 0 to 228903
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   air_store_id    228904 non-null  object
 1   visit_date      228904 non-null  datetime64[ns]
 2   visitors        228904 non-null  int32
 3   calendar_date   228904 non-null  datetime64[ns]
 4   day_of_week     228904 non-null  object
 5   holiday_flg     228904 non-null  int32
 6   air_genre_name  228904 non-null  object
 7   air_area_name   228904 non-null  object
 8   latitude        228904 non-null  float64
 9   longitude       228904 non-null  float64
 10  month           228904 non-null  int32
 11  is_weekend      228904 non-null  int64
 12  lag_1           228904 non-null  float64
 13  lag_7           228904 non-null  float64
 14  lag_14          228904 non-null  float64
 15  lag_28          228904 non-null  float64
 16  roll_mean_7     228904 non-null  float64
 17  roll_std_7      228904 non-null  float64
 18  roll_mean_28    228904 non-null  float64
 19  roll_std_28     228904 non-null  float64
 20  y               228904 non-null  float64
dtypes: datetime64[ns](2), float64(11), int32(3), int64(1), object(4)
memory usage: 34.1+ MB

In [0]:
spark.createDataFrame(df_model).write.format("delta").mode("overwrite") \
    .saveAsTable("workspace.default.features")

In [0]:
spark.sql("SELECT COUNT(*) AS rows FROM workspace.default.features").display()

rows
228904